### ISSUE TITLE
systemd had dropped support for daemon reload.

### ISSUE THREAD

**Issue by Heidistein** [markt-de/puppet-solr#4]
see https://github.com/camptocamp/puppet-systemd/pull/171

**Comment by rbos** [comment]
Seeing the same thing. Module is broken. `Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::systemd::systemctl::daemon_reload`

**Comment by fraenki** [comment]
bugfix available in release 3.0.0
