### ISSUE TITLE
Parameter solr::manage_service_limits without function

### ISSUE THREAD

**Issue by cruelsmith** [markt-de/puppet-solr#8]
The parameter `solr::manage_service_limits` is not used anywhere and does not toggle the management of the `systemd::service_limits` and `limits::limits` resources as the description suggest.

Introduced by https://github.com/markt-de/puppet-solr/commit/fae36d9219fca00298bf8d0871036d28b21dbe08

**Comment by fraenki** [comment]
Thanks for reporting this issue! A fix was released in version 3.1.1.
