### ISSUE TITLE
install_dir

### ISSUE THREAD

**Issue by Stuartacus** [markt-de/puppet-solr#9]
Sorry if this is my error, but I am trying to install and I am getting stuck at:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Solr]: has no parameter named 'install_dir

removing the install_dir option allows the install to continue, however I would like to define a custom installation directory.

Hope that makes sense

**Comment by fraenki** [comment]
Oh, this parameter was removed in 2019, but I forgot to update the README. Fixed. Thanks :)

**Comment by fraenki** [comment]
> removing the install_dir option allows the install to continue, however I would like to define a custom installation directory.

The `$extract_dir` parameter is what you're looking for:
https://github.com/markt-de/puppet-solr/blob/master/REFERENCE.md#extract_dir

**Comment by Stuartacus** [comment]
Thanks Frank, that is really helpful.

Sorry if I am being foolish but I am struggling to create my cores, and
solr isn't starting, could you show me a working example if you have one?

at the minute I just have a tweaked version of your demo as below:

class { 'solr':
    version     => '8.1.0',

    # Allow automatic upgrades (when changing $version)
    upgrade     => true,

    # Network settings
    solr_port   => 8983,
    solr_host   => $facts['networking']['fqdn'],

    # Use custom installation and data directories
    extract_dir => '/opt',
    var_dir     => '/opt/solr-home',
    log_dir     => '/opt/solr-home/log',
    solr_home   => '/opt/solr-home/data',

    # Change Solr runtime parameters
    java_mem    => '-Xms2g -Xmx8g',
    solr_time   => 'Europe/London',
    solr_user   => 'lacddt',
    solr_opts   => [
      '-Duser.language=gb',
      '-Duser.country=GB',
    ],

    # Use an alternative download location (for old versions)
    mirror      => 'https://archive.apache.org/dist/lucene/solr/',
}
solr::service { 'solr.service':
 source => "puppet:///modules/solr/foo.service",
}

I'd be very grateful if you could let me know where I am going wrong.

**Comment by fraenki** [comment]
Well, the output from the (failed) Puppet run would be a good starting point. :)

We're testing Solr using [this manifest](https://github.com/markt-de/puppet-solr/blob/master/spec/acceptance/class_spec.rb#L33-L40), but the example from the README should work too.

**Comment by Stuartacus** [comment]
Sorry Frank, I managed to get the module sunning, I would like to know more
about how to use the private classes to create the solr cores.

It looks ass though solr is working on the server when i launch it manually.

Hope that makes sense.

The puppet runs looks fine as far as I can see.

Thanks, Stuart

**Comment by fraenki** [comment]
This is just not enough information and I don't see a specific question.
The README contains hints how to setup Solr cloud:
https://github.com/markt-de/puppet-solr#solr-cloud

**Comment by Stuartacus** [comment]
BSorry if I was not being clear.

I used a modified version of your example in the readme:

class { 'solr':
    version     => '8.1.0',

    # Allow automatic upgrades (when changing $version)
    upgrade     => true,

    # Network settings
    solr_port   => 8983,
    solr_host   => $facts['networking']['fqdn'],

    # Use custom installation and data directories
    extract_dir => '/opt',
    var_dir     => '/opt/solr-home',
    log_dir     => '/opt/solr-home/log',
    solr_home   => '/opt/solr-home/data',

    # Change Solr runtime parameters
    java_mem    => '-Xms2g -Xmx8g',
    solr_time   => 'Europe/London',
    solr_user   => 'lacddt',
    solr_opts   => [
      '-Duser.language=gb',
      '-Duser.country=GB',
    ],

    # Use an alternative download location (for old versions)
    mirror      => 'https://archive.apache.org/dist/lucene/solr/',
}


In my pp file, but solr doesn't start running (I can start it manually),
there are no errors during the puppet run.

I have experimented with adding:

service { 'solr':
  ensure => 'running',
  enable => true
}

But during the puppet run I get:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER:
Server Error: Evaluation Error: Error while evaluating a Resource
Statement, Duplicate declaration: Service[solr] is already declared at
(file:
/etc/puppetlabs/code/environments/lib_aspace/modules/solr/manifests/service.pp,
line: 27); cannot redeclare (file:
/etc/puppetlabs/code/environments/lib_aspace/site/profile/manifests/archivesspace/archivesspace.pp,
line: 69) (file:
/etc/puppetlabs/code/environments/lib_aspace/site/profile/manifests/archivesspace/archivesspace.pp,
line: 69, column: 3) on node lac-archivesspace-test4.is.ed.ac.uk

I think I have managed to get the core creation right with :

  solr::core { 'archivesspace_core':
  core_name => 'archivesspace',
}


However for now it throws an error because solr isn;t running during the
puppet run.

Q: How can I ensure the solr service is running?

Thanks for your help and sorry if i am not being clear.

Best, Stuart.

**Comment by fraenki** [comment]
> In my pp file, but solr doesn't start running (I can start it manually),
> there are no errors during the puppet run.

If there's no error, then I don't know why it's failing for you. It works in our acceptance tests and in production servers. Maybe it's related to your operating system.
